# (APPENDIX) Appendices {-}

```{r data-methods-setup, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(rprojroot)
library(tidyverse)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment = "")
options("readr.num_columns" = 0)
```

# Data Methods

## King County Lookup Lists
```{r data-methods-kc-lookup}
lu_intro_fp <- root_file("2-communication/1-rnotebooks/00-make-kc-lookup-intro.Rmd")

lu_juris_fp <- root_file('2-communication/1-rnotebooks/00-make-kc-lookup-jurisdiction.Rmd')

lu_tax_reason_fp <- root_file('2-communication/1-rnotebooks/00-make-kc-lookup-tax-reason.Rmd')

# lu_presentuse_fp <- root_file("2-communication/1-rnotebooks/00-make-kc-lookup-presentuse.Rmd")

lu_tax_status_fp <- root_file("2-communication/1-rnotebooks/00-make-kc-lookup-tax-status.Rmd")
```

`r knit_child(lu_intro_fp)`
<br>
<hr>
`r knit_child(lu_juris_fp)`
<br>
<hr>
`r knit_child(lu_tax_reason_fp)`
<br>
<hr> 
<br>
<hr>
`r knit_child(lu_tax_status_fp)`

## Untaxed King County Parcels
```{r data-methods-kc-pub}
kc_tax_0_fp <- root_file("2-communication/1-rnotebooks/00-make-kc-parcels-not-taxed.Rmd")
```

`r knit_child(kc_tax_0_fp)`

## Resources
_This is a work in progress document - changes will be made._
