--- 
always_allow_html: yes
editor_options:
  chunk_output_type: console
output:
  html_document:
    df_print: paged
  html_notebook:
    code_folding: hide
---

```{r make-kc-lookup-juris-setup, warning=FALSE, echo=FALSE, message=FALSE}
library(tidyverse)
library(stringr)
library(sf)
library(googledrive)
library(miscgis)
library(forcats)
library(leaflet)
library(mapview)
library(miscgis)
library(htmltools)
library(snakecase)
library(magrittr)
library(rprojroot)

root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
options(httr_oob_default=TRUE) 
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

### King County Jurisdictions

#### Description {-}

Jurisdiction planning to annex this area. 

#### Links {-}
  - [Source <i class="fa fa-external-link"></i>](http://www5.kingcounty.gov/sdc/Metadata.aspx?Layer=public_parcels) 
   

#### Processing Steps {-}
##### Summary {-}

  1. Create `string`: The contents of the JURISDICTION table copy-and-pasted in the R environment.
  2. Create `juris`: A named vector of the jurisdictions and their abbreviations.
  3. Upload to Drive
  
##### Step 1 {-}

```{r make-kc-lookup-juris-01, echo = TRUE, message=FALSE}

string <- 
"NULL	NULL
AL	Algona
AU	Auburn
BD	Black Diamond
BE	Bellevue
BO	Bothell
BU	Burien
CA	Carnation
CH	Clyde Hill
CO	Covington
DM	Des Moines
DU	Duvall
EN	Enumclaw
FW	Federal Way
HP	Hunts Point
IS	Issaquah
KE	Kent
KI	Kirkland
KM	Kenmore
LF	Lake Forest Park
ME	Medina
MI	Mercer Island
MT	Milton
MV	Maple Valley
NB	North Bend
NC	Newcastle
NP	Normandy Park
PA	Pacific
RM	Redmond
RN	Renton
SE	Seattle
SH	Shoreline
SK	Skykomish
SM	Sammamish
SN	Snoqualmie
ST	SeaTac
TU	Tukwila
WO	Woodinville
YP	Yarrow Point"


```

##### Step 2 {-}

```{r make-kc-lookup-juris-02, echo = TRUE, message=FALSE}

juris <- 
  str_split(string, pattern = "\n") %>% 
  map(~ t(as.data.frame(str_split(.x,pattern = "\t")))) %>% 
  as.data.frame() %>% 
  set_names(c("CODE","NAME")) %>% 
  set_rownames(NULL) %>% 
  mutate_all(as.character) %>%  
  pmap(~ set_names(..2, ..1))

str(juris)
```

##### Step 3 {-}

```{r make-kc-lookup-juris-03, eval = FALSE, echo = TRUE}
folder <- as_id("0B5Pp4V6eCkhrZ3NHOEE0Sl9FbWc")

tmp <- tempfile()

write_rds(juris,tmp)

drive_upload(tmp, folder,name = "kc-jurisdictions.rds")
```
